# Adds customized columns to generated by devise user model
class AddNameSurnamePositionToUser < ActiveRecord::Migration[5.2]
  def change
  	add_column :users, :name, :string
  	add_column :users, :surname, :string
  	add_column :users, :position, :string
  end
end
